# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.


# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
# include: package:flutter_lints/flutter.yaml
include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - /**/*.g.dart

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_redundant_argument_values: true
    prefer_relative_imports: false
    depend_on_referenced_packages: true
    library_private_types_in_public_api: true
    use_build_context_synchronously: true
    # Back to the 80s
    lines_longer_than_80_chars: true

