// Mocks generated by Mockito 5.4.4 from annotations
// in xmanager/test/src/data/repositories/ble_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_blue_plus/flutter_blue_plus.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i6;
import 'package:xmanager/src/data/datasources/local/ble_datasource.dart' as _i2;
import 'package:xmanager/src/data/datasources/local/permissions_datasource.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BleDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleDataSource extends _i1.Mock implements _i2.BleDataSource {
  MockBleDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.ScanResult>> get scanResults => (super.noSuchMethod(
        Invocation.getter(#scanResults),
        returnValue: _i3.Stream<List<_i4.ScanResult>>.empty(),
      ) as _i3.Stream<List<_i4.ScanResult>>);

  @override
  _i3.Stream<bool> get isScanning => (super.noSuchMethod(
        Invocation.getter(#isScanning),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i3.Future<bool> get isSupported => (super.noSuchMethod(
        Invocation.getter(#isSupported),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> startScan(
    int? seconds,
    List<String>? services,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startScan,
          [
            seconds,
            services,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopScan() => (super.noSuchMethod(
        Invocation.method(
          #stopScan,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> turnOn() => (super.noSuchMethod(
        Invocation.method(
          #turnOn,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> connect(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [uuid],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> connectAndDiscoverServices(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectAndDiscoverServices,
          [uuid],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [uuid],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> discoverServices(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #discoverServices,
          [uuid],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<bool> connected(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #connected,
          [uuid],
        ),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i3.Future<bool> isConnected(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [uuid],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<int>> readCharacteristic(
    String? deviceUuid,
    String? serviceUuid,
    String? characteristicsUuid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #readCharacteristic,
          [
            deviceUuid,
            serviceUuid,
            characteristicsUuid,
          ],
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<void> writeCharacteristic(
    String? deviceUuid,
    String? serviceUuid,
    String? characteristicsUuid,
    List<int>? value,
    bool? withoutResponse,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeCharacteristic,
          [
            deviceUuid,
            serviceUuid,
            characteristicsUuid,
            value,
            withoutResponse,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setNotifications(
    String? deviceUuid,
    String? serviceUuid,
    String? characteristicsUuid,
    bool? enable,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotifications,
          [
            deviceUuid,
            serviceUuid,
            characteristicsUuid,
            enable,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<int>> lastValueStream(
    String? deviceUuid,
    String? serviceUuid,
    String? characteristicsUuid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastValueStream,
          [
            deviceUuid,
            serviceUuid,
            characteristicsUuid,
          ],
        ),
        returnValue: _i3.Stream<List<int>>.empty(),
      ) as _i3.Stream<List<int>>);
}

/// A class which mocks [PermissionsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionsDataSource extends _i1.Mock
    implements _i5.PermissionsDataSource {
  MockPermissionsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.Permission>> permissionList() => (super.noSuchMethod(
        Invocation.method(
          #permissionList,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Permission>>.value(<_i6.Permission>[]),
      ) as _i3.Future<List<_i6.Permission>>);

  @override
  _i3.Future<_i6.PermissionStatus> permissionStatus(
          _i6.Permission? permission) =>
      (super.noSuchMethod(
        Invocation.method(
          #permissionStatus,
          [permission],
        ),
        returnValue:
            _i3.Future<_i6.PermissionStatus>.value(_i6.PermissionStatus.denied),
      ) as _i3.Future<_i6.PermissionStatus>);

  @override
  _i3.Future<_i6.PermissionStatus> requestPermission(
          _i6.Permission? permission) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [permission],
        ),
        returnValue:
            _i3.Future<_i6.PermissionStatus>.value(_i6.PermissionStatus.denied),
      ) as _i3.Future<_i6.PermissionStatus>);

  @override
  _i3.Future<_i6.PermissionStatus> requestLocationPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue:
            _i3.Future<_i6.PermissionStatus>.value(_i6.PermissionStatus.denied),
      ) as _i3.Future<_i6.PermissionStatus>);

  @override
  _i3.Future<bool> locationPermissionGranted() => (super.noSuchMethod(
        Invocation.method(
          #locationPermissionGranted,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i6.PermissionStatus> requestBluetoothPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBluetoothPermission,
          [],
        ),
        returnValue:
            _i3.Future<_i6.PermissionStatus>.value(_i6.PermissionStatus.denied),
      ) as _i3.Future<_i6.PermissionStatus>);

  @override
  _i3.Future<bool> bluetoothPermissionGranted() => (super.noSuchMethod(
        Invocation.method(
          #bluetoothPermissionGranted,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i6.PermissionStatus> requestBluetoothConnectPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBluetoothConnectPermission,
          [],
        ),
        returnValue:
            _i3.Future<_i6.PermissionStatus>.value(_i6.PermissionStatus.denied),
      ) as _i3.Future<_i6.PermissionStatus>);

  @override
  _i3.Future<bool> bluetoothConnectPermissionGranted() => (super.noSuchMethod(
        Invocation.method(
          #bluetoothConnectPermissionGranted,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i6.PermissionStatus> requestBluetoothScanPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestBluetoothScanPermission,
          [],
        ),
        returnValue:
            _i3.Future<_i6.PermissionStatus>.value(_i6.PermissionStatus.denied),
      ) as _i3.Future<_i6.PermissionStatus>);

  @override
  _i3.Future<bool> bluetoothScanPermissionGranted() => (super.noSuchMethod(
        Invocation.method(
          #bluetoothScanPermissionGranted,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
