// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4KjRa_1vv807Gy7JrGkDdyw1IRuFK_4k',
    appId: '1:361288387306:android:32205a8965d8ee502ee593',
    messagingSenderId: '361288387306',
    projectId: 'spartans-284709',
    databaseURL: 'https://spartans-284709-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spartans-284709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgsdyIlDAsiFBSxuMZ_ONnVdg__6azmsk',
    appId: '1:361288387306:ios:1455adbeb13a4f852ee593',
    messagingSenderId: '361288387306',
    projectId: 'spartans-284709',
    databaseURL: 'https://spartans-284709-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spartans-284709.appspot.com',
    iosBundleId: 'com.ninespartans.xmanager',
  );
}
