// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 3225004814405648421),
      name: 'Player',
      lastPropertyId: const IdUid(7, 4315454425118091218),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5238429446566774022),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1771857347335397486),
            name: 'role',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3820171138096343296),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4237932649912434568),
            name: 'age',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1269412459972584565),
            name: 'weight',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4315454425118091218),
            name: 'height',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 3225004814405648421),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [813253216084854960],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        8417382096306948866,
        4981195636571552789,
        8396051598652696070,
        5960381172322319033
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Player: EntityDefinition<Player>(
        model: _entities[0],
        toOneRelations: (Player object) => [],
        toManyRelations: (Player object) => {},
        getId: (Player object) => object.id,
        setId: (Player object, int id) {
          object.id = id;
        },
        objectToFB: (Player object, fb.Builder fbb) {
          final roleOffset =
              object.role == null ? null : fbb.writeString(object.role!);
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, roleOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addInt64(4, object.age);
          fbb.addFloat64(5, object.weight);
          fbb.addFloat64(6, object.height);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Player()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..role = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 6)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..age =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12)
            ..weight = const fb.Float64Reader()
                .vTableGetNullable(buffer, rootOffset, 14)
            ..height = const fb.Float64Reader()
                .vTableGetNullable(buffer, rootOffset, 16);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Player] entity fields to define ObjectBox queries.
class Player_ {
  /// see [Player.id]
  static final id = QueryIntegerProperty<Player>(_entities[0].properties[0]);

  /// see [Player.role]
  static final role = QueryStringProperty<Player>(_entities[0].properties[1]);

  /// see [Player.name]
  static final name = QueryStringProperty<Player>(_entities[0].properties[2]);

  /// see [Player.age]
  static final age = QueryIntegerProperty<Player>(_entities[0].properties[3]);

  /// see [Player.weight]
  static final weight = QueryDoubleProperty<Player>(_entities[0].properties[4]);

  /// see [Player.height]
  static final height = QueryDoubleProperty<Player>(_entities[0].properties[5]);
}
