// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/player_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 3225004814405648421),
      name: 'Player',
      lastPropertyId: const IdUid(11, 1941030560164370764),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5238429446566774022),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1771857347335397486),
            name: 'role',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1269412459972584565),
            name: 'weight',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4315454425118091218),
            name: 'height',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 4112552099121775271),
            name: 'fullname',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 4836018249428677867),
            name: 'birthdate',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 1941030560164370764),
            name: 'nationality',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 8116831420168438470),
      name: 'DeviceProgram',
      lastPropertyId: const IdUid(2, 688095002173714801),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5068653949683785411),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 688095002173714801),
            name: 'title',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 3656018098347934602),
      name: 'SessionProgram',
      lastPropertyId: const IdUid(6, 3406376473234597456),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7444579579755250816),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1959944578448247002),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 9109228393002401543),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5281269997235546803),
            name: 'startDate',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4152780086259794751),
            name: 'createdAt',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3406376473234597456),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(4, 3656018098347934602),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [813253216084854960],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        8417382096306948866,
        4981195636571552789,
        8396051598652696070,
        5960381172322319033,
        3820171138096343296,
        4237932649912434568,
        6380926248530783123
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Player: EntityDefinition<Player>(
        model: _entities[0],
        toOneRelations: (Player object) => [],
        toManyRelations: (Player object) => {},
        getId: (Player object) => object.id,
        setId: (Player object, int id) {
          object.id = id;
        },
        objectToFB: (Player object, fb.Builder fbb) {
          final roleOffset =
              object.role == null ? null : fbb.writeString(object.role!);
          final fullnameOffset = fbb.writeString(object.fullname);
          final nationalityOffset = object.nationality == null
              ? null
              : fbb.writeString(object.nationality!);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, roleOffset);
          fbb.addFloat64(5, object.weight);
          fbb.addFloat64(6, object.height);
          fbb.addOffset(7, fullnameOffset);
          fbb.addInt64(9, object.birthdate?.millisecondsSinceEpoch);
          fbb.addOffset(10, nationalityOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final birthdateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22);
          final object = Player()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..role = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 6)
            ..weight = const fb.Float64Reader()
                .vTableGetNullable(buffer, rootOffset, 14)
            ..height = const fb.Float64Reader()
                .vTableGetNullable(buffer, rootOffset, 16)
            ..fullname = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..birthdate = birthdateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(birthdateValue)
            ..nationality = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 24);

          return object;
        }),
    DeviceProgram: EntityDefinition<DeviceProgram>(
        model: _entities[1],
        toOneRelations: (DeviceProgram object) => [],
        toManyRelations: (DeviceProgram object) => {},
        getId: (DeviceProgram object) => object.id,
        setId: (DeviceProgram object, int id) {
          object.id = id;
        },
        objectToFB: (DeviceProgram object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = DeviceProgram()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..title = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '');

          return object;
        }),
    SessionProgram: EntityDefinition<SessionProgram>(
        model: _entities[2],
        toOneRelations: (SessionProgram object) => [],
        toManyRelations: (SessionProgram object) => {},
        getId: (SessionProgram object) => object.id,
        setId: (SessionProgram object, int id) {
          object.id = id;
        },
        objectToFB: (SessionProgram object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addInt64(3, object.startDate?.millisecondsSinceEpoch);
          fbb.addInt64(4, object.createdAt?.millisecondsSinceEpoch);
          fbb.addInt64(5, object.updatedAt?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final startDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final createdAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final updatedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final object = SessionProgram()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..title = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..description = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..startDate = startDateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(startDateValue)
            ..createdAt = createdAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdAtValue)
            ..updatedAt = updatedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Player] entity fields to define ObjectBox queries.
class Player_ {
  /// see [Player.id]
  static final id = QueryIntegerProperty<Player>(_entities[0].properties[0]);

  /// see [Player.role]
  static final role = QueryStringProperty<Player>(_entities[0].properties[1]);

  /// see [Player.weight]
  static final weight = QueryDoubleProperty<Player>(_entities[0].properties[2]);

  /// see [Player.height]
  static final height = QueryDoubleProperty<Player>(_entities[0].properties[3]);

  /// see [Player.fullname]
  static final fullname =
      QueryStringProperty<Player>(_entities[0].properties[4]);

  /// see [Player.birthdate]
  static final birthdate =
      QueryIntegerProperty<Player>(_entities[0].properties[5]);

  /// see [Player.nationality]
  static final nationality =
      QueryStringProperty<Player>(_entities[0].properties[6]);
}

/// [DeviceProgram] entity fields to define ObjectBox queries.
class DeviceProgram_ {
  /// see [DeviceProgram.id]
  static final id =
      QueryIntegerProperty<DeviceProgram>(_entities[1].properties[0]);

  /// see [DeviceProgram.title]
  static final title =
      QueryStringProperty<DeviceProgram>(_entities[1].properties[1]);
}

/// [SessionProgram] entity fields to define ObjectBox queries.
class SessionProgram_ {
  /// see [SessionProgram.id]
  static final id =
      QueryIntegerProperty<SessionProgram>(_entities[2].properties[0]);

  /// see [SessionProgram.title]
  static final title =
      QueryStringProperty<SessionProgram>(_entities[2].properties[1]);

  /// see [SessionProgram.description]
  static final description =
      QueryStringProperty<SessionProgram>(_entities[2].properties[2]);

  /// see [SessionProgram.startDate]
  static final startDate =
      QueryIntegerProperty<SessionProgram>(_entities[2].properties[3]);

  /// see [SessionProgram.createdAt]
  static final createdAt =
      QueryIntegerProperty<SessionProgram>(_entities[2].properties[4]);

  /// see [SessionProgram.updatedAt]
  static final updatedAt =
      QueryIntegerProperty<SessionProgram>(_entities[2].properties[5]);
}
